app1:
	gcc proc_01.c

th1:
	gcc -pthread -o a.out proc_01_th.c

app2:
	gcc proc_02.c

th2:
	gcc -pthread -o a.out proc_02_th.c

th2_2:
	gcc -pthread -o a.out proc_02_th_02.c

app3:
	gcc proc_03.c

th3:
	gcc -pthread -o a.out proc_03_th.c


alena:
	gcc -pthread -o a.out alena_1_th.c